## Site details
site_name: 'Canine Glioma Project'
site_description: 'Canine Glioma Project - Summary and Extended Methods'
site_author: 'Samir B. Amin'
site_url: 'https://canineglioma.verhaaklab.com'
# site_suburl: '/cgp/canine/methods'
nav:
    - Home: index.md
    - Methods:
      - Samples: methods/S01_samples.md
      - Data Sources: methods/S02_data_sources.md
      - Sample Preparations: methods/S03_sample_prep.md
      - Alignments: methods/S04_alignments_fprint.md
      - Somatic SNVs and Indels: methods/S05_somatic_variants.md
      - Significantly Mutated Genes: methods/S06_smgs.md
      - Cancer Hallmarks: methods/S07_hallmarks.md
      - Somatic Mutation Rate: methods/S09_mutation_rate.md
      - Somatic Copy Number Aberrations: methods/S10_SCNA.md
      - Aneuploidy Metrics: methods/S11_aneuploidy.md
      - Intratumor Heterogeneity: methods/S12_ith.md
      - Mutational Signatures: methods/S13_mut_sigs.md
      - Molecular Timing of Somatic Drivers: methods/S14_mut_timing.md
      - Class Prediction using methylation classifier: methods/S15_class_predict_methy.md
      - Immune Microenvironment Analysis: methods/S16_expression_immune.md
    - Contact: https://verhaaklab.com/contact

## Copyright
copyright: 'Copyright &copy; 2017 - 2019 <a href="https://verhaaklab.com">Verhaak Lab at the Jackson Laboratory for Genomic Medicine</a>'

## Configuration
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'IBM Plex Sans'
    code: 'Fira Code'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'
  feature:
    tabs: false

extra_css:
  - 'assets/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'assets/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'

extra:
  disqus: 'verhaaklab'
  social:
    - type: 'envelope'
      link: 'https://verhaaklab.com/contact'
    - type: 'twitter'
      link: 'https://twitter.com/roelverhaak'
    - type: 'github'
      link: 'https://github.com/sbamin'
    - type: 'twitter'
      link: 'https://twitter.com/sbamin'
  search:
    tokenizer: '[\s\-\.]+'
  twittercard:
    user: roelverhaak

# Google Analytics
google_analytics:
  - 'UA-64053990-2'
  - 'auto'

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - meta
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.arithmatex:
  #     generic: true
