############### WORKDIR ################
## path to store results
workdir: "/fastscratch/amins/snakemake/cgp_scna"
## snakemake dir: snakemake must run from this dir
smk_home: "/projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/scripts/snakemake"

############### CLUSTER ################
cluster_specs: "/projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/scripts/snakemake/confs/torque_helix.json"

tempdir: "/fastscratch/amins/tmp"

## path to tools ##
readCounterScript:  /projects/verhaak-lab/verhaak_env/verhaak_apps/hmmcopy_utils/default/bin/readCounter
ichorCNA_rscript:  /projects/verhaak-lab/verhaak_env/verhaak_apps/ichorCNA/scripts/runIchorCNA.R
ichorCNA_libdir:
  /projects/verhaak-lab/verhaak_env/verhaak_apps/ichorCNA/R/
pyCountScript:  /projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/scripts/code/countPysam.py
TitanCNA_rscript: /projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/scripts/R_scripts/titanCNA.R
TitanCNA_selectSolutionRscript: /projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/scripts/R_scripts/selectSolution.R
TitanCNA_libdir:  /projects/verhaak-lab/amins_cgp_level2/copy_number/TitanCNA/

## path to reference files ##
ichorCNA_exons:
  NULL
ichorCNA_centromere:
  /projects/verhaak-lab/DogWGSReference/canfam3.1_gaps/gaps_ucsc_table_canfam3.1.sorted_canonical.bed
refFasta:
  /projects/verhaak-lab/DogWGSReference/CanFam3_1.fa
snpDB:
  /projects/verhaak-lab/DogWGSReference/Canis_familiaris.vcf
TitanCNA_centromere:  /projects/verhaak-lab/DogWGSReference/canfam3.1_gaps/gaps_ucsc_table_canfam3.1.sorted_canonical.bed
## path to tools
samTools:  /projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/envs/rvenv2018/bin/samtools

## reference settings and paths to reference files ##
genomeBuild: canFam3
genomeStyle:  Ensembl
snpVCF:  /projects/verhaak-lab/DogWGSReference/Canis_familiaris.vcf 
ichorCNA_exons: NULL
cytobandFile:  /projects/verhaak-lab/DogWGSReference/cytoband/CanFam3.1_cytobands_nocfa.bed
centromere:  /projects/verhaak-lab/DogWGSReference/canfam3.1_gaps/gaps_ucsc_table_canfam3.1.sorted_canonical.bed
sex:  None   # use None if both females and males are in sample set

## standard parameters for qsub memory, runtime, pe (parallel environment)
# use what your scheduler designates for parameters; does not apply to local run
# invoke using:
# snakemake -s TitanCNA.snakefile --cluster-sync "qsub -l h_vmem={params.mem},h_rt={params.runtime} {params.pe}" -j 100 --jobscript config/cluster.sh
std_mem:  8196
std_runtime:  "05:00:00"
std_numCores:  4

## params for each step ##

## read depth params ##
chrs:
  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,X
binSize:  1000

## ichorCNA params ##
ichorCNA_gcWig: /projects/verhaak-lab/DogWGSReference/mappability/hmmcopy/gc_count/CanFam3_1.gc.ws1kb_39chrs.wig
ichorCNA_mapWig:  /projects/verhaak-lab/DogWGSReference/mappability/hmmcopy/mapcounts/CanFam3_1.mapcounts.100bw.ws1kb_39chrs.wig
ichorCNA_chrs:  c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38, \"X\")
ichorCNA_chrTrain:  c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38, \"X\")  
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  4
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)
ichorCNA_genomeStyle: Ensembl
ichorCNA_useChrY: FALSE
ichorCNA_species: Canis_familiaris
ichorCNA_rmCentromereFlankLength: 0
ichorCNA_mem:  8196
ichorCNA_runtime:  "05:00:00"
ichorCNA_pe: 4  

## allele counts - samtools, pysam ##
# USERS MUST MODIFY getAlleleCounts.snakefile to use the correct CHRS naming
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_numCores: 10
TitanCNA_maxNumClonalClusters: 5
TitanCNA_chrs:  c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_gender: unknown
TitanCNA_verbosity: TRUE
TitanCNA_hetHeader: FALSE
TitanCNA_centFlankLength: 0
TitanCNA_drawPlots: TRUE
TitanCNA_mem:  8196
TitanCNA_runtime:  "05:00:00"
TitanCNA_pe: 4 
